name: Scheduled Python Workflow

on:
  schedule:
    - cron: '*/5 * * * *'  # Set your desired cron schedule here to run every 5 minutes
  workflow_dispatch:  # Enable the workflow to be manually triggered

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Choose the Python version you want to use

    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Use the relative path to the requirements.txt file

    - name: Run Python script
      # run: echo "${{ vars.URL }} ${{ vars.MARKETS }}. Today is ${{ vars.AGENCIES }}!"
      run: python test.py  # Specify the relative path to your Python script in the repository
