name: Scheduled Python Workflow

on:
  schedule:
    - cron: '*/1 * * * *'  # Set your desired cron schedule here

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Choose the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # pip install -r requirements.txt  # if you have any requirements

    - name: Run Python script
      run: python   test.py # Specify the path to your Python script
