name: Scheduled Python Workflow

on:
  # schedule:
  #   - cron: '*/5 * * * *'  # Set your desired cron schedule here to run every 5 minutes
  workflow_dispatch:  # Enable the workflow to be manually triggered

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'  # Choose the Python version you want to use

    - name: Checkout repository
      uses: actions/checkout@v2
      with:
          token: ${{ secrets.GITHUB_TOKEN }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt  # Use the relative path to the requirements.txt file
    
    - name: Run Python script
      env :
          URL: ${{ vars.URL}}
          MARKETS: ${{ vars.MARKETS }}
          AGENCIES: ${{ vars.AGENCIES }}
      # run: echo "${{ vars.URL }} ${{ vars.MARKETS }}. Today is ${{ vars.AGENCIES }}!"
      run: python test.py >>README.md # Specify the relative path to your Python script in the repository
    - name: Commit changes and push to repository
      run: |
        git config --global user.email "you@example.com"
        git config --global user.name "mohit"
        git add README.md
        git commit -m "updating README.md"
        git push https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/mohitchaniyal/testingWorkFlow.git HEAD:main
